/* Generated by the F54 contract fixture generator.  */
/* { dg-do compile } */
/* { dg-options "-O2 -march=rv32im_zicsr_ztt0p6 -mabi=ilp32 -mztt-profile=gcc-runtime-u8-m32-a16 -fmax-errors=0 -Werror=implicit-function-declaration" { target rv32 } } */
/* { dg-options "-O2 -march=rv64im_zicsr_ztt0p6 -mabi=lp64 -mztt-profile=gcc-runtime-u8-m32-a16 -fmax-errors=0 -Werror=implicit-function-declaration" { target rv64 } } */
#include <stddef.h>
#include <stdint.h>
#include <riscv_ztt.h>

/* ame_acquire:01: Missing desc argument (spec line 1226).  */
void
case_ame_acquire_01 (size_t runtime_index)
{
  (void) __riscv_ztt_ame_acquire(); /* { dg-error "too few arguments" } */
}

/* ame_acquire:02: desc cannot be an M value (spec line 1227).  */
void
case_ame_acquire_02 (size_t runtime_index)
{
  __riscv_ztt_i32_1x1_t src_i32_1x1 = __riscv_ztt_mzero_m_i32_1x1 ();
  (void) __riscv_ztt_ame_acquire(src_i32_1x1); /* { dg-error "incompatible type for argument" } */
}

/* ame_release:01: Interface takes no arguments (spec line 1269).  */
void
case_ame_release_01 (size_t runtime_index)
{
  (void) __riscv_ztt_ame_release(0); /* { dg-error "too many arguments" } */
}

/* ame_release:02: Interface returns no value (spec line 1270).  */
void
case_ame_release_02 (size_t runtime_index)
{
  size_t result = __riscv_ztt_ame_release(); /* { dg-error "void value not ignored" } */
}
