/* Generated by the F54 contract fixture generator.  */
/* { dg-do compile } */
/* { dg-options "-O2 -march=rv32im_zicsr_ztt0p6 -mabi=ilp32 -mztt-profile=gcc-runtime-u8-m32-a16 -fmax-errors=0 -Werror=implicit-function-declaration" { target rv32 } } */
/* { dg-options "-O2 -march=rv64im_zicsr_ztt0p6 -mabi=lp64 -mztt-profile=gcc-runtime-u8-m32-a16 -fmax-errors=0 -Werror=implicit-function-declaration" { target rv64 } } */
#include <stddef.h>
#include <stdint.h>
#include <riscv_ztt.h>

/* Legal counterpart of mextract:01; its result is observable.  */
void
positive_mextract_01 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x4_t src_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mextract_i16_1x2(src_i16_1x4, 0);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mextract:02; its result is observable.  */
void
positive_mextract_02 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x4_t src_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mextract_i16_1x2(src_i16_1x4, 0);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mextract:03; its result is observable.  */
void
positive_mextract_03 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x4_t src_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mextract_i16_1x2(src_i16_1x4, 0);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mextract:04; its result is observable.  */
void
positive_mextract_04 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x4_t src_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mextract_i16_1x2(src_i16_1x4, 1);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mextract:05; its result is observable.  */
void
positive_mextract_05 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x4_t src_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mextract_i16_1x2(src_i16_1x4, 1);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mconcat:01; its result is observable.  */
void
positive_mconcat_01 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src1_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x2_t src2_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x4_t dst = __riscv_ztt_mconcat_m_i16_1x4(src1_i16_1x2, src2_i16_1x2);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mconcat:02; its result is observable.  */
void
positive_mconcat_02 (void *out, size_t runtime_index)
{
  __riscv_ztt_i32_1x2_t src1_i32_1x2 = __riscv_ztt_mzero_m_i32_1x2 ();
  __riscv_ztt_i32_1x2_t src2_i32_1x2 = __riscv_ztt_mzero_m_i32_1x2 ();
  __riscv_ztt_i32_1x4_t dst = __riscv_ztt_mconcat_m_i32_1x4(src1_i32_1x2, src2_i32_1x2);
  __riscv_ztt_mss_rm ((int32_t *) out, dst);
}

/* Legal counterpart of mconcat:03; its result is observable.  */
void
positive_mconcat_03 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src1_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x2_t src2_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x4_t dst = __riscv_ztt_mconcat_m_i16_1x4(src1_i16_1x2, src2_i16_1x2);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mconcat:04; its result is observable.  */
void
positive_mconcat_04 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src1_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x2_t src2_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x4_t dst = __riscv_ztt_mconcat_m_i16_1x4(src1_i16_1x2, src2_i16_1x2);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mconcat:05; its result is observable.  */
void
positive_mconcat_05 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x4_t src1_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  __riscv_ztt_i16_1x4_t src2_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  __riscv_ztt_i16_1x8_t dst = __riscv_ztt_mconcat_m_i16_1x8(src1_i16_1x4, src2_i16_1x4);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mconcat:06; its result is observable.  */
void
positive_mconcat_06 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_2x1_t src1_i16_2x1 = __riscv_ztt_mzero_m_i16_2x1 ();
  __riscv_ztt_i16_2x1_t src2_i16_2x1 = __riscv_ztt_mzero_m_i16_2x1 ();
  __riscv_ztt_i16_4x1_t dst = __riscv_ztt_mconcat_m_i16_4x1(src1_i16_2x1, src2_i16_2x1);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mcopy_m2m:01; its result is observable.  */
void
positive_mcopy_m2m_01 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mcopy_m2m_i16_1x2(src_i16_1x2);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mcopy_m2m:02; its result is observable.  */
void
positive_mcopy_m2m_02 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mcopy_m2m_i16_1x2(src_i16_1x2);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mcopy_m2m:03; its result is observable.  */
void
positive_mcopy_m2m_03 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mcopy_m2m_i16_1x2(src_i16_1x2);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mcopy_a2m:01; its result is observable.  */
void
positive_mcopy_a2m_01 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t acc_i16_accx2 = __riscv_ztt_mzero_acc_i16_accx2 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mcopy_a2m_i16_1x2(acc_i16_accx2);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mcopy_a2m:02; its result is observable.  */
void
positive_mcopy_a2m_02 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t acc_i16_accx2 = __riscv_ztt_mzero_acc_i16_accx2 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mcopy_a2m_i16_1x2(acc_i16_accx2);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mcopy_a2m:03; its result is observable.  */
void
positive_mcopy_a2m_03 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t acc_i16_accx2 = __riscv_ztt_mzero_acc_i16_accx2 ();
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mcopy_a2m_i16_1x2(acc_i16_accx2);
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mcopy_m2a:01; its result is observable.  */
void
positive_mcopy_m2a_01 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_accx2_t dst = __riscv_ztt_mcopy_m2a_i16_accx2(src_i16_1x2);
  __riscv_ztt_i16_1x2_t m = __riscv_ztt_mcopy_a2m_i16_1x2 (dst);
  __riscv_ztt_mss_rm ((int16_t *) out, m);
}

/* Legal counterpart of mcopy_m2a:02; its result is observable.  */
void
positive_mcopy_m2a_02 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_accx2_t dst = __riscv_ztt_mcopy_m2a_i16_accx2(src_i16_1x2);
  __riscv_ztt_i16_1x2_t m = __riscv_ztt_mcopy_a2m_i16_1x2 (dst);
  __riscv_ztt_mss_rm ((int16_t *) out, m);
}

/* Legal counterpart of mcopy_m2a:03; its result is observable.  */
void
positive_mcopy_m2a_03 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_accx2_t dst = __riscv_ztt_mcopy_m2a_i16_accx2(src_i16_1x2);
  __riscv_ztt_i16_1x2_t m = __riscv_ztt_mcopy_a2m_i16_1x2 (dst);
  __riscv_ztt_mss_rm ((int16_t *) out, m);
}

/* Legal counterpart of mclear_m:01; its result is observable.  */
void
positive_mclear_m_01 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mclear_m_i16_1x2();
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mclear_m:02; its result is observable.  */
void
positive_mclear_m_02 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mclear_m_i16_1x2();
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mclear_acc:01; its result is observable.  */
void
positive_mclear_acc_01 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t dst = __riscv_ztt_mclear_acc_i16_accx2();
  __riscv_ztt_i16_1x2_t m = __riscv_ztt_mcopy_a2m_i16_1x2 (dst);
  __riscv_ztt_mss_rm ((int16_t *) out, m);
}

/* Legal counterpart of mclear_acc:02; its result is observable.  */
void
positive_mclear_acc_02 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t dst = __riscv_ztt_mclear_acc_i16_accx2();
  __riscv_ztt_i16_1x2_t m = __riscv_ztt_mcopy_a2m_i16_1x2 (dst);
  __riscv_ztt_mss_rm ((int16_t *) out, m);
}

/* Legal counterpart of mzero_m:01; its result is observable.  */
void
positive_mzero_m_01 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mzero_m_i16_1x2();
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mzero_m:02; its result is observable.  */
void
positive_mzero_m_02 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t dst = __riscv_ztt_mzero_m_i16_1x2();
  __riscv_ztt_mss_rm ((int16_t *) out, dst);
}

/* Legal counterpart of mzero_acc:01; its result is observable.  */
void
positive_mzero_acc_01 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t dst = __riscv_ztt_mzero_acc_i16_accx2();
  __riscv_ztt_i16_1x2_t m = __riscv_ztt_mcopy_a2m_i16_1x2 (dst);
  __riscv_ztt_mss_rm ((int16_t *) out, m);
}

/* Legal counterpart of mzero_acc:02; its result is observable.  */
void
positive_mzero_acc_02 (void *out, size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t dst = __riscv_ztt_mzero_acc_i16_accx2();
  __riscv_ztt_i16_1x2_t m = __riscv_ztt_mcopy_a2m_i16_1x2 (dst);
  __riscv_ztt_mss_rm ((int16_t *) out, m);
}

/* Legal counterpart of ame_acquire:01; its result is observable.  */
void
positive_ame_acquire_01 (void *out, size_t runtime_index)
{
  *(size_t *) out = __riscv_ztt_ame_acquire(runtime_index);
}

/* Legal counterpart of ame_acquire:02; its result is observable.  */
void
positive_ame_acquire_02 (void *out, size_t runtime_index)
{
  *(size_t *) out = __riscv_ztt_ame_acquire(runtime_index);
}

/* Legal counterpart of ame_release:01; its result is observable.  */
void
positive_ame_release_01 (void *out, size_t runtime_index)
{
  __riscv_ztt_ame_release();
}

/* Legal counterpart of ame_release:02; its result is observable.  */
void
positive_ame_release_02 (void *out, size_t runtime_index)
{
  __riscv_ztt_ame_release();
}

/* { dg-final { scan-assembler {msettyp} } } */
/* { dg-final { scan-assembler {mss\.rm} } } */
/* { dg-final { scan-assembler {mmov\.m\.a} } } */
/* { dg-final { scan-assembler {mmov\.a\.m} } } */
/* { dg-final { scan-assembler {ame\.acquire} } } */
/* { dg-final { scan-assembler {ame\.release} } } */
