/* { dg-do compile } */
/* { dg-options "-g -std=gnu++11 -march=rv32gc_ztt0p6 -mabi=ilp32d -mztt-profile=gcc-runtime-u32-m16-a4" { target rv32 } } */
/* { dg-options "-g -std=gnu++11 -march=rv64gc_ztt0p6 -mabi=lp64d -mztt-profile=gcc-runtime-u32-m16-a4" { target rv64 } } */
#include "../../../../../gcc.target/riscv/ame/calls/ztt-call-owned-body.h"
/* { dg-final { check-function-bodies "**" "" } } */
/*
** owned_kernel:
** ...
** csrr\s+s11,amenlen
** ...
** mss\.1r\s+.*
** ...
** call\s+call_boundary
** ...
** mls\.1r\s+.*
** ...
*/
/*
** owned_region:
** ...
** ame\.acquire\s+.*
** ...
** andi\s+[^,]+,[^,]+,1
** ...
** call\s+owned_kernel
** ...
** ame\.release
** ...
*/
/* { dg-final { scan-assembler-times {ame\.acquire} 2 } } */
/* { dg-final { scan-assembler-times {ame\.release} 2 } } */
/* { dg-final { scan-assembler-times {csrr\s+s11,amenlen} 1 } } */
