/* { dg-do compile } */
/* { dg-options "-g -std=gnu99 -march=rv32gc_ztt0p6 -mabi=ilp32d -mztt-profile=gcc-runtime-u32-m16-a4" { target rv32 } } */
/* { dg-options "-g -std=gnu99 -march=rv64gc_ztt0p6 -mabi=lp64d -mztt-profile=gcc-runtime-u32-m16-a4" { target rv64 } } */
#define CALL_TC i32
#define CALL_ELEMENT int32_t
#include "../ztt-call-body.h"
/* { dg-final { check-function-bodies "**" "" } } */
/*
** matrix_call:
** ...
** mss\.1r\s+.*
** ...
** call\s+call_boundary
** ...
** mls\.1r\s+.*
** ...
*/
/*
** accumulator_call:
** ...
** agettyp\s+.*
** ...
** mss\.1r\s+.*
** ...
** call\s+call_boundary
** ...
** mls\.1r\s+.*
** ...
** asettyp\s+.*
** ...
*/
/* { dg-final { scan-assembler {\.cfi_offset 1,} } } */
