/* Generated by the F54 contract fixture generator.  */
/* { dg-do compile } */
/* { dg-options "-O2 -march=rv32im_zicsr_ztt0p6 -mabi=ilp32 -mztt-profile=gcc-runtime-u8-m32-a16 -fmax-errors=0 -Werror=implicit-function-declaration" { target rv32 } } */
/* { dg-options "-O2 -march=rv64im_zicsr_ztt0p6 -mabi=lp64 -mztt-profile=gcc-runtime-u8-m32-a16 -fmax-errors=0 -Werror=implicit-function-declaration" { target rv64 } } */
#include <stddef.h>
#include <stdint.h>
#include <riscv_ztt.h>

/* mclear_m:01: Unsupported 2x2 shape (spec line 674).  */
void
case_mclear_m_01 (size_t runtime_index)
{
  (void) __riscv_ztt_mclear_m_i16_2x2(); /* { dg-error "implicit declaration" } */
}

/* mclear_acc:01: Unsupported accx3 shape (spec line 743).  */
void
case_mclear_acc_01 (size_t runtime_index)
{
  (void) __riscv_ztt_mclear_acc_i16_accx3(); /* { dg-error "implicit declaration" } */
}

/* mzero_m:01: Unsupported 2x2 shape (spec line 813).  */
void
case_mzero_m_01 (size_t runtime_index)
{
  (void) __riscv_ztt_mzero_m_i16_2x2(); /* { dg-error "implicit declaration" } */
}

/* mzero_acc:01: Unsupported accx3 shape (spec line 887).  */
void
case_mzero_acc_01 (size_t runtime_index)
{
  (void) __riscv_ztt_mzero_acc_i16_accx3(); /* { dg-error "implicit declaration" } */
}
