/* Generated by F55 generate-catalog.py.  */
/* { dg-do compile } */
/* { dg-options "-O2 -march=rv32im_zicsr_ztt0p6 -mabi=ilp32 -mztt-profile=gcc-runtime-u128-m16-a4" { target rv32 } } */
/* { dg-options "-O2 -march=rv64im_zicsr_ztt0p6 -mabi=lp64 -mztt-profile=gcc-runtime-u128-m16-a4" { target rv64 } } */
#include <riscv_ztt.h>

/* Scalar availability must not require an available same-TC 1x1 M type.  */
typedef char size_i8_rnu[(sizeof (__riscv_ztt_i8_rnu_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i8_rnu (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i8_rnu
    (__riscv_ztt_scalar_from_bits_i8_rnu (x));
}
typedef char size_i8_rnu_sat[(sizeof (__riscv_ztt_i8_rnu_sat_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i8_rnu_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i8_rnu_sat
    (__riscv_ztt_scalar_from_bits_i8_rnu_sat (x));
}
typedef char size_i8_rne[(sizeof (__riscv_ztt_i8_rne_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i8_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i8_rne
    (__riscv_ztt_scalar_from_bits_i8_rne (x));
}
typedef char size_i8_rne_sat[(sizeof (__riscv_ztt_i8_rne_sat_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i8_rne_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i8_rne_sat
    (__riscv_ztt_scalar_from_bits_i8_rne_sat (x));
}
typedef char size_i8_rdn[(sizeof (__riscv_ztt_i8_rdn_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i8_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i8_rdn
    (__riscv_ztt_scalar_from_bits_i8_rdn (x));
}
typedef char size_i8_rdn_sat[(sizeof (__riscv_ztt_i8_rdn_sat_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i8_rdn_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i8_rdn_sat
    (__riscv_ztt_scalar_from_bits_i8_rdn_sat (x));
}
typedef char size_i8_rod[(sizeof (__riscv_ztt_i8_rod_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i8_rod (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i8_rod
    (__riscv_ztt_scalar_from_bits_i8_rod (x));
}
typedef char size_i8_rod_sat[(sizeof (__riscv_ztt_i8_rod_sat_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i8_rod_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i8_rod_sat
    (__riscv_ztt_scalar_from_bits_i8_rod_sat (x));
}
typedef char size_u8_rnu[(sizeof (__riscv_ztt_u8_rnu_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u8_rnu (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u8_rnu
    (__riscv_ztt_scalar_from_bits_u8_rnu (x));
}
typedef char size_u8_rnu_sat[(sizeof (__riscv_ztt_u8_rnu_sat_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u8_rnu_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u8_rnu_sat
    (__riscv_ztt_scalar_from_bits_u8_rnu_sat (x));
}
typedef char size_u8_rne[(sizeof (__riscv_ztt_u8_rne_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u8_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u8_rne
    (__riscv_ztt_scalar_from_bits_u8_rne (x));
}
typedef char size_u8_rne_sat[(sizeof (__riscv_ztt_u8_rne_sat_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u8_rne_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u8_rne_sat
    (__riscv_ztt_scalar_from_bits_u8_rne_sat (x));
}
typedef char size_u8_rdn[(sizeof (__riscv_ztt_u8_rdn_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u8_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u8_rdn
    (__riscv_ztt_scalar_from_bits_u8_rdn (x));
}
typedef char size_u8_rdn_sat[(sizeof (__riscv_ztt_u8_rdn_sat_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u8_rdn_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u8_rdn_sat
    (__riscv_ztt_scalar_from_bits_u8_rdn_sat (x));
}
typedef char size_u8_rod[(sizeof (__riscv_ztt_u8_rod_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u8_rod (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u8_rod
    (__riscv_ztt_scalar_from_bits_u8_rod (x));
}
typedef char size_u8_rod_sat[(sizeof (__riscv_ztt_u8_rod_sat_scalar_t)
  == (8 < __riscv_xlen ? 8 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u8_rod_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u8_rod_sat
    (__riscv_ztt_scalar_from_bits_u8_rod_sat (x));
}
typedef char size_i16_rnu[(sizeof (__riscv_ztt_i16_rnu_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i16_rnu (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i16_rnu
    (__riscv_ztt_scalar_from_bits_i16_rnu (x));
}
typedef char size_i16_rnu_sat[(sizeof (__riscv_ztt_i16_rnu_sat_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i16_rnu_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i16_rnu_sat
    (__riscv_ztt_scalar_from_bits_i16_rnu_sat (x));
}
typedef char size_i16_rne[(sizeof (__riscv_ztt_i16_rne_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i16_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i16_rne
    (__riscv_ztt_scalar_from_bits_i16_rne (x));
}
typedef char size_i16_rne_sat[(sizeof (__riscv_ztt_i16_rne_sat_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i16_rne_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i16_rne_sat
    (__riscv_ztt_scalar_from_bits_i16_rne_sat (x));
}
typedef char size_i16_rdn[(sizeof (__riscv_ztt_i16_rdn_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i16_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i16_rdn
    (__riscv_ztt_scalar_from_bits_i16_rdn (x));
}
typedef char size_i16_rdn_sat[(sizeof (__riscv_ztt_i16_rdn_sat_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i16_rdn_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i16_rdn_sat
    (__riscv_ztt_scalar_from_bits_i16_rdn_sat (x));
}
typedef char size_i16_rod[(sizeof (__riscv_ztt_i16_rod_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i16_rod (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i16_rod
    (__riscv_ztt_scalar_from_bits_i16_rod (x));
}
typedef char size_i16_rod_sat[(sizeof (__riscv_ztt_i16_rod_sat_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i16_rod_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i16_rod_sat
    (__riscv_ztt_scalar_from_bits_i16_rod_sat (x));
}
typedef char size_u16_rnu[(sizeof (__riscv_ztt_u16_rnu_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u16_rnu (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u16_rnu
    (__riscv_ztt_scalar_from_bits_u16_rnu (x));
}
typedef char size_u16_rnu_sat[(sizeof (__riscv_ztt_u16_rnu_sat_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u16_rnu_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u16_rnu_sat
    (__riscv_ztt_scalar_from_bits_u16_rnu_sat (x));
}
typedef char size_u16_rne[(sizeof (__riscv_ztt_u16_rne_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u16_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u16_rne
    (__riscv_ztt_scalar_from_bits_u16_rne (x));
}
typedef char size_u16_rne_sat[(sizeof (__riscv_ztt_u16_rne_sat_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u16_rne_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u16_rne_sat
    (__riscv_ztt_scalar_from_bits_u16_rne_sat (x));
}
typedef char size_u16_rdn[(sizeof (__riscv_ztt_u16_rdn_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u16_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u16_rdn
    (__riscv_ztt_scalar_from_bits_u16_rdn (x));
}
typedef char size_u16_rdn_sat[(sizeof (__riscv_ztt_u16_rdn_sat_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u16_rdn_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u16_rdn_sat
    (__riscv_ztt_scalar_from_bits_u16_rdn_sat (x));
}
typedef char size_u16_rod[(sizeof (__riscv_ztt_u16_rod_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u16_rod (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u16_rod
    (__riscv_ztt_scalar_from_bits_u16_rod (x));
}
typedef char size_u16_rod_sat[(sizeof (__riscv_ztt_u16_rod_sat_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u16_rod_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u16_rod_sat
    (__riscv_ztt_scalar_from_bits_u16_rod_sat (x));
}
typedef char size_i32_rnu[(sizeof (__riscv_ztt_i32_rnu_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i32_rnu (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i32_rnu
    (__riscv_ztt_scalar_from_bits_i32_rnu (x));
}
typedef char size_i32_rnu_sat[(sizeof (__riscv_ztt_i32_rnu_sat_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i32_rnu_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i32_rnu_sat
    (__riscv_ztt_scalar_from_bits_i32_rnu_sat (x));
}
typedef char size_i32_rne[(sizeof (__riscv_ztt_i32_rne_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i32_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i32_rne
    (__riscv_ztt_scalar_from_bits_i32_rne (x));
}
typedef char size_i32_rne_sat[(sizeof (__riscv_ztt_i32_rne_sat_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i32_rne_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i32_rne_sat
    (__riscv_ztt_scalar_from_bits_i32_rne_sat (x));
}
typedef char size_i32_rdn[(sizeof (__riscv_ztt_i32_rdn_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i32_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i32_rdn
    (__riscv_ztt_scalar_from_bits_i32_rdn (x));
}
typedef char size_i32_rdn_sat[(sizeof (__riscv_ztt_i32_rdn_sat_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i32_rdn_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i32_rdn_sat
    (__riscv_ztt_scalar_from_bits_i32_rdn_sat (x));
}
typedef char size_i32_rod[(sizeof (__riscv_ztt_i32_rod_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i32_rod (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i32_rod
    (__riscv_ztt_scalar_from_bits_i32_rod (x));
}
typedef char size_i32_rod_sat[(sizeof (__riscv_ztt_i32_rod_sat_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i32_rod_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i32_rod_sat
    (__riscv_ztt_scalar_from_bits_i32_rod_sat (x));
}
typedef char size_u32_rnu[(sizeof (__riscv_ztt_u32_rnu_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u32_rnu (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u32_rnu
    (__riscv_ztt_scalar_from_bits_u32_rnu (x));
}
typedef char size_u32_rnu_sat[(sizeof (__riscv_ztt_u32_rnu_sat_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u32_rnu_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u32_rnu_sat
    (__riscv_ztt_scalar_from_bits_u32_rnu_sat (x));
}
typedef char size_u32_rne[(sizeof (__riscv_ztt_u32_rne_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u32_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u32_rne
    (__riscv_ztt_scalar_from_bits_u32_rne (x));
}
typedef char size_u32_rne_sat[(sizeof (__riscv_ztt_u32_rne_sat_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u32_rne_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u32_rne_sat
    (__riscv_ztt_scalar_from_bits_u32_rne_sat (x));
}
typedef char size_u32_rdn[(sizeof (__riscv_ztt_u32_rdn_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u32_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u32_rdn
    (__riscv_ztt_scalar_from_bits_u32_rdn (x));
}
typedef char size_u32_rdn_sat[(sizeof (__riscv_ztt_u32_rdn_sat_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u32_rdn_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u32_rdn_sat
    (__riscv_ztt_scalar_from_bits_u32_rdn_sat (x));
}
typedef char size_u32_rod[(sizeof (__riscv_ztt_u32_rod_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u32_rod (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u32_rod
    (__riscv_ztt_scalar_from_bits_u32_rod (x));
}
typedef char size_u32_rod_sat[(sizeof (__riscv_ztt_u32_rod_sat_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u32_rod_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u32_rod_sat
    (__riscv_ztt_scalar_from_bits_u32_rod_sat (x));
}
typedef char size_i64_rnu[(sizeof (__riscv_ztt_i64_rnu_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i64_rnu (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i64_rnu
    (__riscv_ztt_scalar_from_bits_i64_rnu (x));
}
typedef char size_i64_rnu_sat[(sizeof (__riscv_ztt_i64_rnu_sat_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i64_rnu_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i64_rnu_sat
    (__riscv_ztt_scalar_from_bits_i64_rnu_sat (x));
}
typedef char size_i64_rne[(sizeof (__riscv_ztt_i64_rne_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i64_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i64_rne
    (__riscv_ztt_scalar_from_bits_i64_rne (x));
}
typedef char size_i64_rne_sat[(sizeof (__riscv_ztt_i64_rne_sat_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i64_rne_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i64_rne_sat
    (__riscv_ztt_scalar_from_bits_i64_rne_sat (x));
}
typedef char size_i64_rdn[(sizeof (__riscv_ztt_i64_rdn_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i64_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i64_rdn
    (__riscv_ztt_scalar_from_bits_i64_rdn (x));
}
typedef char size_i64_rdn_sat[(sizeof (__riscv_ztt_i64_rdn_sat_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i64_rdn_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i64_rdn_sat
    (__riscv_ztt_scalar_from_bits_i64_rdn_sat (x));
}
typedef char size_i64_rod[(sizeof (__riscv_ztt_i64_rod_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i64_rod (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i64_rod
    (__riscv_ztt_scalar_from_bits_i64_rod (x));
}
typedef char size_i64_rod_sat[(sizeof (__riscv_ztt_i64_rod_sat_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i64_rod_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i64_rod_sat
    (__riscv_ztt_scalar_from_bits_i64_rod_sat (x));
}
typedef char size_u64_rnu[(sizeof (__riscv_ztt_u64_rnu_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u64_rnu (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u64_rnu
    (__riscv_ztt_scalar_from_bits_u64_rnu (x));
}
typedef char size_u64_rnu_sat[(sizeof (__riscv_ztt_u64_rnu_sat_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u64_rnu_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u64_rnu_sat
    (__riscv_ztt_scalar_from_bits_u64_rnu_sat (x));
}
typedef char size_u64_rne[(sizeof (__riscv_ztt_u64_rne_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u64_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u64_rne
    (__riscv_ztt_scalar_from_bits_u64_rne (x));
}
typedef char size_u64_rne_sat[(sizeof (__riscv_ztt_u64_rne_sat_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u64_rne_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u64_rne_sat
    (__riscv_ztt_scalar_from_bits_u64_rne_sat (x));
}
typedef char size_u64_rdn[(sizeof (__riscv_ztt_u64_rdn_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u64_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u64_rdn
    (__riscv_ztt_scalar_from_bits_u64_rdn (x));
}
typedef char size_u64_rdn_sat[(sizeof (__riscv_ztt_u64_rdn_sat_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u64_rdn_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u64_rdn_sat
    (__riscv_ztt_scalar_from_bits_u64_rdn_sat (x));
}
typedef char size_u64_rod[(sizeof (__riscv_ztt_u64_rod_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u64_rod (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u64_rod
    (__riscv_ztt_scalar_from_bits_u64_rod (x));
}
typedef char size_u64_rod_sat[(sizeof (__riscv_ztt_u64_rod_sat_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u64_rod_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u64_rod_sat
    (__riscv_ztt_scalar_from_bits_u64_rod_sat (x));
}
typedef char size_i128_rnu[(sizeof (__riscv_ztt_i128_rnu_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i128_rnu (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i128_rnu
    (__riscv_ztt_scalar_from_bits_i128_rnu (x));
}
typedef char size_i128_rnu_sat[(sizeof (__riscv_ztt_i128_rnu_sat_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i128_rnu_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i128_rnu_sat
    (__riscv_ztt_scalar_from_bits_i128_rnu_sat (x));
}
typedef char size_i128_rne[(sizeof (__riscv_ztt_i128_rne_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i128_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i128_rne
    (__riscv_ztt_scalar_from_bits_i128_rne (x));
}
typedef char size_i128_rne_sat[(sizeof (__riscv_ztt_i128_rne_sat_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i128_rne_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i128_rne_sat
    (__riscv_ztt_scalar_from_bits_i128_rne_sat (x));
}
typedef char size_i128_rdn[(sizeof (__riscv_ztt_i128_rdn_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i128_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i128_rdn
    (__riscv_ztt_scalar_from_bits_i128_rdn (x));
}
typedef char size_i128_rdn_sat[(sizeof (__riscv_ztt_i128_rdn_sat_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i128_rdn_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i128_rdn_sat
    (__riscv_ztt_scalar_from_bits_i128_rdn_sat (x));
}
typedef char size_i128_rod[(sizeof (__riscv_ztt_i128_rod_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i128_rod (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i128_rod
    (__riscv_ztt_scalar_from_bits_i128_rod (x));
}
typedef char size_i128_rod_sat[(sizeof (__riscv_ztt_i128_rod_sat_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_i128_rod_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_i128_rod_sat
    (__riscv_ztt_scalar_from_bits_i128_rod_sat (x));
}
typedef char size_u128_rnu[(sizeof (__riscv_ztt_u128_rnu_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u128_rnu (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u128_rnu
    (__riscv_ztt_scalar_from_bits_u128_rnu (x));
}
typedef char size_u128_rnu_sat[(sizeof (__riscv_ztt_u128_rnu_sat_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u128_rnu_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u128_rnu_sat
    (__riscv_ztt_scalar_from_bits_u128_rnu_sat (x));
}
typedef char size_u128_rne[(sizeof (__riscv_ztt_u128_rne_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u128_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u128_rne
    (__riscv_ztt_scalar_from_bits_u128_rne (x));
}
typedef char size_u128_rne_sat[(sizeof (__riscv_ztt_u128_rne_sat_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u128_rne_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u128_rne_sat
    (__riscv_ztt_scalar_from_bits_u128_rne_sat (x));
}
typedef char size_u128_rdn[(sizeof (__riscv_ztt_u128_rdn_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u128_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u128_rdn
    (__riscv_ztt_scalar_from_bits_u128_rdn (x));
}
typedef char size_u128_rdn_sat[(sizeof (__riscv_ztt_u128_rdn_sat_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u128_rdn_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u128_rdn_sat
    (__riscv_ztt_scalar_from_bits_u128_rdn_sat (x));
}
typedef char size_u128_rod[(sizeof (__riscv_ztt_u128_rod_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u128_rod (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u128_rod
    (__riscv_ztt_scalar_from_bits_u128_rod (x));
}
typedef char size_u128_rod_sat[(sizeof (__riscv_ztt_u128_rod_sat_scalar_t)
  == (128 < __riscv_xlen ? 128 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_u128_rod_sat (unsigned long x)
{
  return __riscv_ztt_scalar_bits_u128_rod_sat
    (__riscv_ztt_scalar_from_bits_u128_rod_sat (x));
}
typedef char size_f16_rne[(sizeof (__riscv_ztt_f16_rne_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f16_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f16_rne
    (__riscv_ztt_scalar_from_bits_f16_rne (x));
}
typedef char size_f16_rtz[(sizeof (__riscv_ztt_f16_rtz_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f16_rtz (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f16_rtz
    (__riscv_ztt_scalar_from_bits_f16_rtz (x));
}
typedef char size_f16_rdn[(sizeof (__riscv_ztt_f16_rdn_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f16_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f16_rdn
    (__riscv_ztt_scalar_from_bits_f16_rdn (x));
}
typedef char size_f16_rup[(sizeof (__riscv_ztt_f16_rup_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f16_rup (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f16_rup
    (__riscv_ztt_scalar_from_bits_f16_rup (x));
}
typedef char size_f16_rmm[(sizeof (__riscv_ztt_f16_rmm_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f16_rmm (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f16_rmm
    (__riscv_ztt_scalar_from_bits_f16_rmm (x));
}
typedef char size_f16_rno[(sizeof (__riscv_ztt_f16_rno_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f16_rno (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f16_rno
    (__riscv_ztt_scalar_from_bits_f16_rno (x));
}
typedef char size_bf16_rne[(sizeof (__riscv_ztt_bf16_rne_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_bf16_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_bf16_rne
    (__riscv_ztt_scalar_from_bits_bf16_rne (x));
}
typedef char size_bf16_rtz[(sizeof (__riscv_ztt_bf16_rtz_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_bf16_rtz (unsigned long x)
{
  return __riscv_ztt_scalar_bits_bf16_rtz
    (__riscv_ztt_scalar_from_bits_bf16_rtz (x));
}
typedef char size_bf16_rdn[(sizeof (__riscv_ztt_bf16_rdn_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_bf16_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_bf16_rdn
    (__riscv_ztt_scalar_from_bits_bf16_rdn (x));
}
typedef char size_bf16_rup[(sizeof (__riscv_ztt_bf16_rup_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_bf16_rup (unsigned long x)
{
  return __riscv_ztt_scalar_bits_bf16_rup
    (__riscv_ztt_scalar_from_bits_bf16_rup (x));
}
typedef char size_bf16_rmm[(sizeof (__riscv_ztt_bf16_rmm_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_bf16_rmm (unsigned long x)
{
  return __riscv_ztt_scalar_bits_bf16_rmm
    (__riscv_ztt_scalar_from_bits_bf16_rmm (x));
}
typedef char size_bf16_rno[(sizeof (__riscv_ztt_bf16_rno_scalar_t)
  == (16 < __riscv_xlen ? 16 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_bf16_rno (unsigned long x)
{
  return __riscv_ztt_scalar_bits_bf16_rno
    (__riscv_ztt_scalar_from_bits_bf16_rno (x));
}
typedef char size_f32_rne[(sizeof (__riscv_ztt_f32_rne_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f32_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f32_rne
    (__riscv_ztt_scalar_from_bits_f32_rne (x));
}
typedef char size_f32_rtz[(sizeof (__riscv_ztt_f32_rtz_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f32_rtz (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f32_rtz
    (__riscv_ztt_scalar_from_bits_f32_rtz (x));
}
typedef char size_f32_rdn[(sizeof (__riscv_ztt_f32_rdn_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f32_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f32_rdn
    (__riscv_ztt_scalar_from_bits_f32_rdn (x));
}
typedef char size_f32_rup[(sizeof (__riscv_ztt_f32_rup_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f32_rup (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f32_rup
    (__riscv_ztt_scalar_from_bits_f32_rup (x));
}
typedef char size_f32_rmm[(sizeof (__riscv_ztt_f32_rmm_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f32_rmm (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f32_rmm
    (__riscv_ztt_scalar_from_bits_f32_rmm (x));
}
typedef char size_f32_rno[(sizeof (__riscv_ztt_f32_rno_scalar_t)
  == (32 < __riscv_xlen ? 32 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f32_rno (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f32_rno
    (__riscv_ztt_scalar_from_bits_f32_rno (x));
}
typedef char size_f64_rne[(sizeof (__riscv_ztt_f64_rne_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f64_rne (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f64_rne
    (__riscv_ztt_scalar_from_bits_f64_rne (x));
}
typedef char size_f64_rtz[(sizeof (__riscv_ztt_f64_rtz_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f64_rtz (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f64_rtz
    (__riscv_ztt_scalar_from_bits_f64_rtz (x));
}
typedef char size_f64_rdn[(sizeof (__riscv_ztt_f64_rdn_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f64_rdn (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f64_rdn
    (__riscv_ztt_scalar_from_bits_f64_rdn (x));
}
typedef char size_f64_rup[(sizeof (__riscv_ztt_f64_rup_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f64_rup (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f64_rup
    (__riscv_ztt_scalar_from_bits_f64_rup (x));
}
typedef char size_f64_rmm[(sizeof (__riscv_ztt_f64_rmm_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f64_rmm (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f64_rmm
    (__riscv_ztt_scalar_from_bits_f64_rmm (x));
}
typedef char size_f64_rno[(sizeof (__riscv_ztt_f64_rno_scalar_t)
  == (64 < __riscv_xlen ? 64 : __riscv_xlen) / 8) ? 1 : -1];
unsigned long bits_f64_rno (unsigned long x)
{
  return __riscv_ztt_scalar_bits_f64_rno
    (__riscv_ztt_scalar_from_bits_f64_rno (x));
}
