/* Generated by the F54 contract fixture generator.  */
/* { dg-do compile } */
/* { dg-options "-O2 -march=rv32im_zicsr_ztt0p6 -mabi=ilp32 -mztt-profile=gcc-runtime-u8-m32-a16 -fmax-errors=0" { target rv32 } } */
/* { dg-options "-O2 -march=rv64im_zicsr_ztt0p6 -mabi=lp64 -mztt-profile=gcc-runtime-u8-m32-a16 -fmax-errors=0" { target rv64 } } */
#include <stddef.h>
#include <stdint.h>
#include <riscv_ztt.h>

/* mextract:01: Source and result element types differ (spec line 258).  */
void
case_mextract_01 (size_t runtime_index)
{
  __riscv_ztt_i32_1x4_t src_i32_1x4 = __riscv_ztt_mzero_m_i32_1x4 ();
  (void) __riscv_ztt_mextract_i16_1x2(src_i32_1x4, 0); /* { dg-error "cannot convert" } */
}

/* mextract:02: Result is not half the source (spec line 259).  */
void
case_mextract_02 (size_t runtime_index)
{
  __riscv_ztt_i16_1x8_t src_i16_1x8 = __riscv_ztt_mzero_m_i16_1x8 ();
  (void) __riscv_ztt_mextract_i16_1x2(src_i16_1x8, 0); /* { dg-error "cannot convert" } */
}

/* mextract:03: Shape orientations differ (spec line 260).  */
void
case_mextract_03 (size_t runtime_index)
{
  __riscv_ztt_i16_4x1_t src_i16_4x1 = __riscv_ztt_mzero_m_i16_4x1 ();
  (void) __riscv_ztt_mextract_i16_1x2(src_i16_4x1, 0); /* { dg-error "cannot convert" } */
}

/* mextract:04: index must be 0 or 1 (spec line 261).  */
void
case_mextract_04 (size_t runtime_index)
{
  __riscv_ztt_i16_1x4_t src_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  (void) __riscv_ztt_mextract_i16_1x2(src_i16_1x4, 2); /* { dg-error "mextract index must be an integer constant 0 or 1" } */
}

/* mextract:05: index must be a compile-time constant (spec line 262).  */
void
case_mextract_05 (size_t runtime_index)
{
  __riscv_ztt_i16_1x4_t src_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  (void) __riscv_ztt_mextract_i16_1x2(src_i16_1x4, runtime_index); /* { dg-error "mextract index must be an integer constant 0 or 1" } */
}

/* mconcat:01: Input element types differ (spec line 340).  */
void
case_mconcat_01 (size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src1_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i32_1x2_t src2_i32_1x2 = __riscv_ztt_mzero_m_i32_1x2 ();
  (void) __riscv_ztt_mconcat_m_i16_1x4(src1_i16_1x2, src2_i32_1x2); /* { dg-error "cannot convert" } */
}

/* mconcat:02: Input and result element types differ (spec line 341).  */
void
case_mconcat_02 (size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src1_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x2_t src2_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  (void) __riscv_ztt_mconcat_m_i32_1x4(src1_i16_1x2, src2_i16_1x2); /* { dg-error "cannot convert" } */
}

/* mconcat:03: Input shapes differ (spec line 342).  */
void
case_mconcat_03 (size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src1_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x4_t src2_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  (void) __riscv_ztt_mconcat_m_i16_1x4(src1_i16_1x2, src2_i16_1x4); /* { dg-error "cannot convert" } */
}

/* mconcat:04: Input shape orientations differ (spec line 343).  */
void
case_mconcat_04 (size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src1_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_2x1_t src2_i16_2x1 = __riscv_ztt_mzero_m_i16_2x1 ();
  (void) __riscv_ztt_mconcat_m_i16_1x4(src1_i16_1x2, src2_i16_2x1); /* { dg-error "cannot convert" } */
}

/* mconcat:05: Result shape is not twice the input (spec line 344).  */
void
case_mconcat_05 (size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src1_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x2_t src2_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  (void) __riscv_ztt_mconcat_m_i16_1x8(src1_i16_1x2, src2_i16_1x2); /* { dg-error "cannot convert" } */
}

/* mconcat:06: Result shape orientation differs (spec line 345).  */
void
case_mconcat_06 (size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src1_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  __riscv_ztt_i16_1x2_t src2_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  (void) __riscv_ztt_mconcat_m_i16_4x1(src1_i16_1x2, src2_i16_1x2); /* { dg-error "cannot convert" } */
}

/* mcopy_m2m:01: Source and result element types differ (spec line 436).  */
void
case_mcopy_m2m_01 (size_t runtime_index)
{
  __riscv_ztt_i32_1x2_t src_i32_1x2 = __riscv_ztt_mzero_m_i32_1x2 ();
  (void) __riscv_ztt_mcopy_m2m_i16_1x2(src_i32_1x2); /* { dg-error "cannot convert" } */
}

/* mcopy_m2m:02: Source and result shapes differ (spec line 437).  */
void
case_mcopy_m2m_02 (size_t runtime_index)
{
  __riscv_ztt_i16_1x4_t src_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  (void) __riscv_ztt_mcopy_m2m_i16_1x2(src_i16_1x4); /* { dg-error "cannot convert" } */
}

/* mcopy_m2m:03: Source must be an M value (spec line 438).  */
void
case_mcopy_m2m_03 (size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t acc_i16_accx2 = __riscv_ztt_mzero_acc_i16_accx2 ();
  (void) __riscv_ztt_mcopy_m2m_i16_1x2(acc_i16_accx2); /* { dg-error "cannot convert" } */
}

/* mcopy_a2m:01: Source and result element types differ (spec line 515).  */
void
case_mcopy_a2m_01 (size_t runtime_index)
{
  __riscv_ztt_i32_accx2_t acc_i32_accx2 = __riscv_ztt_mzero_acc_i32_accx2 ();
  (void) __riscv_ztt_mcopy_a2m_i16_1x2(acc_i32_accx2); /* { dg-error "cannot convert" } */
}

/* mcopy_a2m:02: Source and result square counts differ (spec line 516).  */
void
case_mcopy_a2m_02 (size_t runtime_index)
{
  __riscv_ztt_i16_accx4_t acc_i16_accx4 = __riscv_ztt_mzero_acc_i16_accx4 ();
  (void) __riscv_ztt_mcopy_a2m_i16_1x2(acc_i16_accx4); /* { dg-error "cannot convert" } */
}

/* mcopy_a2m:03: Source must be an ACC value (spec line 517).  */
void
case_mcopy_a2m_03 (size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  (void) __riscv_ztt_mcopy_a2m_i16_1x2(src_i16_1x2); /* { dg-error "cannot convert" } */
}

/* mcopy_m2a:01: Source and result element types differ (spec line 594).  */
void
case_mcopy_m2a_01 (size_t runtime_index)
{
  __riscv_ztt_i32_1x2_t src_i32_1x2 = __riscv_ztt_mzero_m_i32_1x2 ();
  (void) __riscv_ztt_mcopy_m2a_i16_accx2(src_i32_1x2); /* { dg-error "cannot convert" } */
}

/* mcopy_m2a:02: Source and result square counts differ (spec line 595).  */
void
case_mcopy_m2a_02 (size_t runtime_index)
{
  __riscv_ztt_i16_1x4_t src_i16_1x4 = __riscv_ztt_mzero_m_i16_1x4 ();
  (void) __riscv_ztt_mcopy_m2a_i16_accx2(src_i16_1x4); /* { dg-error "cannot convert" } */
}

/* mcopy_m2a:03: Source must be an M value (spec line 596).  */
void
case_mcopy_m2a_03 (size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t acc_i16_accx2 = __riscv_ztt_mzero_acc_i16_accx2 ();
  (void) __riscv_ztt_mcopy_m2a_i16_accx2(acc_i16_accx2); /* { dg-error "cannot convert" } */
}

/* mclear_m:02: Interface takes no arguments (spec line 675).  */
void
case_mclear_m_02 (size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  (void) __riscv_ztt_mclear_m_i16_1x2(src_i16_1x2); /* { dg-error "too many arguments" } */
}

/* mclear_acc:02: Interface takes no arguments (spec line 744).  */
void
case_mclear_acc_02 (size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t acc_i16_accx2 = __riscv_ztt_mzero_acc_i16_accx2 ();
  (void) __riscv_ztt_mclear_acc_i16_accx2(acc_i16_accx2); /* { dg-error "too many arguments" } */
}

/* mzero_m:02: Interface takes no arguments (spec line 814).  */
void
case_mzero_m_02 (size_t runtime_index)
{
  __riscv_ztt_i16_1x2_t src_i16_1x2 = __riscv_ztt_mzero_m_i16_1x2 ();
  (void) __riscv_ztt_mzero_m_i16_1x2(src_i16_1x2); /* { dg-error "too many arguments" } */
}

/* mzero_acc:02: Interface takes no arguments (spec line 888).  */
void
case_mzero_acc_02 (size_t runtime_index)
{
  __riscv_ztt_i16_accx2_t acc_i16_accx2 = __riscv_ztt_mzero_acc_i16_accx2 ();
  (void) __riscv_ztt_mzero_acc_i16_accx2(acc_i16_accx2); /* { dg-error "too many arguments" } */
}
